{{- /* Check Subnet Existence and Readiness */ -}}
{{- $subnet := lookup "network.azure.com/v1api20201101" "VirtualNetworksSubnet" .Release.Namespace .Values.subnet.name -}}
{{- $subnetState := dict "ready" false -}}
{{- if and $subnet $subnet.status -}}
  {{- range $subnet.status.conditions -}}
    {{- if and (eq .type "Ready") (eq .status "True") -}}
      {{- $_ := set $subnetState "ready" true -}}
    {{- end -}}
  {{- end -}}
{{- end -}}

{{- if $subnetState.ready }}
apiVersion: network.azure.com/v1api20201101
kind: NetworkInterface
metadata:
  name: {{ .Values.networkInterface.name }}
  namespace: {{ .Release.Namespace }}
spec:
  location: {{ .Values.armRegionName }}
  owner:
    name: {{ .Values.resourceGroup.name }}
  ipConfigurations:
    - name: {{ .Values.networkInterface.ipConfigurationName }}
      privateIPAllocationMethod: Dynamic
      subnet:
        reference:
          group: network.azure.com
          kind: VirtualNetworksSubnet
          name: {{ .Values.subnet.name }}
{{- end }}